= Supply Chain Security: An OpenCAE Resource
Dr. Ahmed Elnoshokaty <aelno@nmu.edu>;Dr. Jim Marquardson <jimarqua@nmu.edu>
v0.1, 2020-01-31
:toc:

== License

This eBook is licensed using Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0). You are encouraged to contribute improvements at https://github.com/jimmarq/opencae.

==  Executive Summary

Describe the topic one or two paragraphs.

== About the Authors

Dr. Ahmed Elnoshokaty is an Assistant Professor of Business Analytics at Northern Michigan University.

Dr. Jim Marquardson in an Assistant Professor of Information Assurance and Cyber Defense at Northern Michigan University.

== Changelog

* 2019-02-01: v1. First version released.

== Executive Summary

Information systems are increasingly being developed by skilled people across the globe. Some organizations hire employees who work in foreign countries to develop code--a process known as offshoring. Offshoring is typically pursued to reduce development costs. Organizations can also choose to outsource development to 3rd parties. Outsourcing can help organizations develop systems when they lack the resources to do the development themselves. Outsourcing can be to a 3rd party in the same country as the organization or a foreign country.

Organizations must carefully consider security and legal implications of global development. Technology components, like physical products, are subject to export control laws. Some software cannot be legally transmitted to certain foreign countries based. In the United States, software can be classified using Export Control Classification Numbers (ECCN). ECCNs can be used to determine where software can legally be transferred. When sourcing software and hardware globally, organizations must also take steps to ensure that malicious code or unapproved hardware modules are not introduced.

As software and hardware are distributed globally, attackers can try to analyze security mechanisms by using software and hardware reverse engineering. In software reverse engineering, researchers take compiled binaries and determine the code routines. Some applications can be decompiled in which source code is generated for a compiled binary application. Hardware circuits can also be analyzed to determine their functions. Weaknesses in software and hardware can be used for future exploits.

Organization must have controls in pace to ensure that development practices reach the intended functionality goals while maintaining security of the systems developed.

== Learning Outcomes

Students should be able to footnote:[https://www.iad.gov/nietp/CAERequirements.cfm]:

1. Describe the issues related to outsourcing hardware and/or software development and/or integration.
2. Describe methods to mitigate these issues, and the limitations of these methods.

== Topics at a Glance

[width="100%",cols="1,2"]
|=====================================
|1. Global Development                         | Organizations leverage information technology skills available in many countries across the globe to develop information systems. Global development can be achieved through outsourcing or offshoring.
|2. Off Shore Production                       | Offshoring is the practice of having systems developed in countries outside of an organization's home country. The main driver for offshoring  is typically lower cost of production.
|3. Transport and Logistics of IT Components   | Collaboration and workflow technology helps enable the transport and logistics of information technology components. Organizations must obey all laws, such as export control, when transporting information technology components.
|4. Evaluation of 3rd Party Development Practices | When outsourcing work to 3rd parties, organizations are still resposible for ensuring that the final product meets all technical requirements.
|5. Understanding of the Capabilities and Limits of Software and Hardware Reverse Engineering| Software reverse engineering is the process of decompiling binary code into source code. Hardware reverse engineering is the analysis of physical computer components to determine their functionality. Attackers can reverse engineer software and hardware to examine and/or bypass security mechanisms.
|=====================================

== Global Development

TODO

== Off Shore Production

TODO

== Transport and Logistics of IT Components

TODO

== Evaluation of 3rd Party Development Practices

TODO

== Software Reverse Engineering

TODO

=== Capabilities

TODO

=== Limits

TODO

== Hardware Reverse Engineering

TODO

=== Capabilities

TODO

=== Limits

TODO