= Style Guide

This document describes the standard format that all eBooks should follow when published in this responsitory.

== File Types

All eBooks should be written in AsciiDoc. The files will be compiled using the AsciiDoctor-PDF ruby gem.

== Titles

The titles of each eBook should follow the format: "Knowledge Unit: An OpenCAE Resource." For example, "Basic Networking: An OpenCAE Resource."

== Authors

Primary authors will be listed. These authors may choose to accept changes proposed by others through pull requests, but only the primary authors will be listed as authors.

== Sections

Each eBook should contain the following major sections:

. License. The license must be Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0).
. Executive Summary. Describe the topic in one or two paragraphs.
. Learning Outcomes. Copy the outcomes as listed in the CAE-CD knowledge unit.
. Topics at a Glance. Include the a table of the knowledge unit topics and a brief (1-3 sentence) definition of the topic. The topic should use the numbered outline as written in the knowledge unit description.

The rest of the document should contain sections and subsections as appropriate to present the material in the knowledge unit. These sections do not necessarily need to follow the order in the knowledge unit topic outline.

== Citations

All citations should be done using AsciiDoc footnotes. Below is an example syntax for a footnote. APA citation style is preferred, but not required.

```
The SHA-2 algorithm was designed by the United States National Security Agency footnote:[https://en.wikipedia.org/wiki/SHA-2].
```

The above code would be rendered as:

The SHA-2 algorithm was designed by the United States National Security Agency footnote:[https://en.wikipedia.org/wiki/SHA-2].

== Use of Images

Any included images must respect copyright. Wherever possible, images should be created from scratch to avoid copyright problems. For diagrams, the yEd diagramming software with the .graphml file format is preferred. Diagrams should be exported to .png files for inclusion in the eBooks.

== Plagiarism

All work should be original. Even though content may exist in other resources that allow for the reuse of material (such as Wikipedia), it is expected that authors create novel work.

